# Its important to understand the distinction from
# build time and run time for an image and container respectively.
# The only image we build in this file is the quail image.
#
# All variables in the .env file are exposed to this docker-compose.yaml
# at when running 'docker-compose up'. You can see how the file looks when
# it has all variable substitutions done with 'docker-compose config'.
# The only variables that persist to runtime are those in the environment
# block for each service.

version: '3'
services:
  quail:
    image: quail:hcv
    command: cron -f
    depends_on:
      - postgres
    volumes:
      - quail_data:/home/hcvprod/quailroot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CAPPY_CLONE_URL: ${PIP_CAPPY_CLONE_URL}
        QUAIL_CLONE_URL: ${PIP_QUAIL_CLONE_URL}
        PGPASSWORD: ${POSTGRES_PASSWORD}
        MINUTE: ${QUAIL_MINUTE}
        HOUR: ${QUAIL_HOUR}
    environment:
      TOKEN: ${QUAIL_TOKEN}
      REDCAP_URL: ${QUAIL_REDCAP_URL}
    restart: always

  postgres:
    image: 'postgres'
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDASH_PASSWORD: ${REDASH_PASSWORD}
    restart: always

  pg_admin:
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"
    environment:
      DEFAULT_USER: ${PG_ADMIN_DEFAULT_USER}
      DEFAULT_PASSWORD: ${PG_ADMIN_DEFAULT_PASS} 
    volumes:
      - pg_admin_data:/var/lib/pgadmin
      - ./init_sql:/docker-entrypoint-initdb.d/
    restart: always

  redash:
    image: redash/redash:latest
    volumes:
      - quail_data:/hcvprod
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: ${REDASH_DATABASE_URL}
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
      REDASH_WEB_WORKERS: 4
    restart: always

  worker:
    image: redash/redash:latest
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: ${REDASH_DATABASE_URL}
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
    restart: always

  redis:
    image: redis:3.0-alpine
    restart: always
    volumes:
      - redis_data:/data

  nginx:
    image: redash/nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - redash
    links:
      - redash:redash
    restart: always
  mysql-server:
    image: mysql
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_DATABASE=malignant"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "3306:3306"
volumes:
  postgres_data:
  pg_admin_data:
  quail_data:
  redis_data:
